// GENERATED by tools/gen_arrangements.py — do not edit by hand.
enum GeneratedArrangements {
    typealias Case = (level: String, name: String, panels: [(scene: String?, chars: [String])])
    static let all: [Case] = [
    (level: "pompey_death", name: "SOLVED__harbor-pompey.ptolemy__egypt_court-caesar.ptolemy", panels: [(scene: "harbor", chars: ["pompey", "ptolemy"]), (scene: "egypt_court", chars: ["caesar", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__egypt_court-caesar.pompey__harbor-caesar.pompey", panels: [(scene: "egypt_court", chars: ["caesar", "pompey"]), (scene: "harbor", chars: ["caesar", "pompey"])]),
    (level: "pompey_death", name: "wrong__egypt_court-caesar.pompey__harbor-caesar.ptolemy", panels: [(scene: "egypt_court", chars: ["caesar", "pompey"]), (scene: "harbor", chars: ["caesar", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__egypt_court-caesar.pompey__harbor-pompey.ptolemy", panels: [(scene: "egypt_court", chars: ["caesar", "pompey"]), (scene: "harbor", chars: ["pompey", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__egypt_court-caesar.ptolemy__harbor-caesar.pompey", panels: [(scene: "egypt_court", chars: ["caesar", "ptolemy"]), (scene: "harbor", chars: ["caesar", "pompey"])]),
    (level: "pompey_death", name: "wrong__egypt_court-caesar.ptolemy__harbor-caesar.ptolemy", panels: [(scene: "egypt_court", chars: ["caesar", "ptolemy"]), (scene: "harbor", chars: ["caesar", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__egypt_court-caesar.ptolemy__harbor-pompey.ptolemy", panels: [(scene: "egypt_court", chars: ["caesar", "ptolemy"]), (scene: "harbor", chars: ["pompey", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__egypt_court-pompey.ptolemy__harbor-caesar.pompey", panels: [(scene: "egypt_court", chars: ["pompey", "ptolemy"]), (scene: "harbor", chars: ["caesar", "pompey"])]),
    (level: "pompey_death", name: "wrong__egypt_court-pompey.ptolemy__harbor-caesar.ptolemy", panels: [(scene: "egypt_court", chars: ["pompey", "ptolemy"]), (scene: "harbor", chars: ["caesar", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__egypt_court-pompey.ptolemy__harbor-pompey.ptolemy", panels: [(scene: "egypt_court", chars: ["pompey", "ptolemy"]), (scene: "harbor", chars: ["pompey", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__harbor-caesar.pompey__egypt_court-caesar.pompey", panels: [(scene: "harbor", chars: ["caesar", "pompey"]), (scene: "egypt_court", chars: ["caesar", "pompey"])]),
    (level: "pompey_death", name: "wrong__harbor-caesar.pompey__egypt_court-caesar.ptolemy", panels: [(scene: "harbor", chars: ["caesar", "pompey"]), (scene: "egypt_court", chars: ["caesar", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__harbor-caesar.pompey__egypt_court-pompey.ptolemy", panels: [(scene: "harbor", chars: ["caesar", "pompey"]), (scene: "egypt_court", chars: ["pompey", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__harbor-caesar.ptolemy__egypt_court-caesar.pompey", panels: [(scene: "harbor", chars: ["caesar", "ptolemy"]), (scene: "egypt_court", chars: ["caesar", "pompey"])]),
    (level: "pompey_death", name: "wrong__harbor-caesar.ptolemy__egypt_court-caesar.ptolemy", panels: [(scene: "harbor", chars: ["caesar", "ptolemy"]), (scene: "egypt_court", chars: ["caesar", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__harbor-caesar.ptolemy__egypt_court-pompey.ptolemy", panels: [(scene: "harbor", chars: ["caesar", "ptolemy"]), (scene: "egypt_court", chars: ["pompey", "ptolemy"])]),
    (level: "pompey_death", name: "wrong__harbor-pompey.ptolemy__egypt_court-caesar.pompey", panels: [(scene: "harbor", chars: ["pompey", "ptolemy"]), (scene: "egypt_court", chars: ["caesar", "pompey"])]),
    (level: "pompey_death", name: "wrong__harbor-pompey.ptolemy__egypt_court-pompey.ptolemy", panels: [(scene: "harbor", chars: ["pompey", "ptolemy"]), (scene: "egypt_court", chars: ["pompey", "ptolemy"])]),
    ]
}
