// GENERATED by tools/gen_arrangements.py — do not edit by hand.
enum GeneratedArrangements {
    typealias Case = (level: String, name: String, panels: [(scene: String?, chars: [String])])
    static let all: [Case] = [
    (level: "rubicon", name: "SOLVED__forum-caesar.antony__rubicon_march-caesar.pompey", panels: [(scene: "forum", chars: ["caesar", "antony"]), (scene: "rubicon_march", chars: ["caesar", "pompey"])]),
    (level: "rubicon", name: "SOLVED__rubicon_march-caesar.pompey__forum-caesar.antony", panels: [(scene: "rubicon_march", chars: ["caesar", "pompey"]), (scene: "forum", chars: ["caesar", "antony"])]),
    (level: "rubicon", name: "wrong__forum-antony.pompey__rubicon_march-antony.pompey", panels: [(scene: "forum", chars: ["antony", "pompey"]), (scene: "rubicon_march", chars: ["antony", "pompey"])]),
    (level: "rubicon", name: "wrong__forum-antony.pompey__rubicon_march-caesar.antony", panels: [(scene: "forum", chars: ["antony", "pompey"]), (scene: "rubicon_march", chars: ["caesar", "antony"])]),
    (level: "rubicon", name: "wrong__forum-antony.pompey__rubicon_march-caesar.pompey", panels: [(scene: "forum", chars: ["antony", "pompey"]), (scene: "rubicon_march", chars: ["caesar", "pompey"])]),
    (level: "rubicon", name: "wrong__forum-caesar.antony__rubicon_march-antony.pompey", panels: [(scene: "forum", chars: ["caesar", "antony"]), (scene: "rubicon_march", chars: ["antony", "pompey"])]),
    (level: "rubicon", name: "wrong__forum-caesar.antony__rubicon_march-caesar.antony", panels: [(scene: "forum", chars: ["caesar", "antony"]), (scene: "rubicon_march", chars: ["caesar", "antony"])]),
    (level: "rubicon", name: "wrong__forum-caesar.pompey__rubicon_march-antony.pompey", panels: [(scene: "forum", chars: ["caesar", "pompey"]), (scene: "rubicon_march", chars: ["antony", "pompey"])]),
    (level: "rubicon", name: "wrong__forum-caesar.pompey__rubicon_march-caesar.antony", panels: [(scene: "forum", chars: ["caesar", "pompey"]), (scene: "rubicon_march", chars: ["caesar", "antony"])]),
    (level: "rubicon", name: "wrong__forum-caesar.pompey__rubicon_march-caesar.pompey", panels: [(scene: "forum", chars: ["caesar", "pompey"]), (scene: "rubicon_march", chars: ["caesar", "pompey"])]),
    (level: "rubicon", name: "wrong__rubicon_march-antony.pompey__forum-antony.pompey", panels: [(scene: "rubicon_march", chars: ["antony", "pompey"]), (scene: "forum", chars: ["antony", "pompey"])]),
    (level: "rubicon", name: "wrong__rubicon_march-antony.pompey__forum-caesar.antony", panels: [(scene: "rubicon_march", chars: ["antony", "pompey"]), (scene: "forum", chars: ["caesar", "antony"])]),
    (level: "rubicon", name: "wrong__rubicon_march-antony.pompey__forum-caesar.pompey", panels: [(scene: "rubicon_march", chars: ["antony", "pompey"]), (scene: "forum", chars: ["caesar", "pompey"])]),
    (level: "rubicon", name: "wrong__rubicon_march-caesar.antony__forum-antony.pompey", panels: [(scene: "rubicon_march", chars: ["caesar", "antony"]), (scene: "forum", chars: ["antony", "pompey"])]),
    (level: "rubicon", name: "wrong__rubicon_march-caesar.antony__forum-caesar.antony", panels: [(scene: "rubicon_march", chars: ["caesar", "antony"]), (scene: "forum", chars: ["caesar", "antony"])]),
    (level: "rubicon", name: "wrong__rubicon_march-caesar.antony__forum-caesar.pompey", panels: [(scene: "rubicon_march", chars: ["caesar", "antony"]), (scene: "forum", chars: ["caesar", "pompey"])]),
    (level: "rubicon", name: "wrong__rubicon_march-caesar.pompey__forum-antony.pompey", panels: [(scene: "rubicon_march", chars: ["caesar", "pompey"]), (scene: "forum", chars: ["antony", "pompey"])]),
    (level: "rubicon", name: "wrong__rubicon_march-caesar.pompey__forum-caesar.pompey", panels: [(scene: "rubicon_march", chars: ["caesar", "pompey"]), (scene: "forum", chars: ["caesar", "pompey"])]),
    ]
}
