// GENERATED by tools/gen_arrangements.py — do not edit by hand.
enum GeneratedArrangements {
    typealias Case = (level: String, name: String, panels: [(scene: String?, chars: [String])])
    static let all: [Case] = [
    (level: "pharsalus", name: "SOLVED__pharsalus_line-caesar.antony__pharsalus_field-caesar.pompey", panels: [(scene: "pharsalus_line", chars: ["caesar", "antony"]), (scene: "pharsalus_field", chars: ["caesar", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-antony.pompey__pharsalus_line-antony.pompey", panels: [(scene: "pharsalus_field", chars: ["antony", "pompey"]), (scene: "pharsalus_line", chars: ["antony", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-antony.pompey__pharsalus_line-caesar.antony", panels: [(scene: "pharsalus_field", chars: ["antony", "pompey"]), (scene: "pharsalus_line", chars: ["caesar", "antony"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-antony.pompey__pharsalus_line-caesar.pompey", panels: [(scene: "pharsalus_field", chars: ["antony", "pompey"]), (scene: "pharsalus_line", chars: ["caesar", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-caesar.antony__pharsalus_line-antony.pompey", panels: [(scene: "pharsalus_field", chars: ["caesar", "antony"]), (scene: "pharsalus_line", chars: ["antony", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-caesar.antony__pharsalus_line-caesar.antony", panels: [(scene: "pharsalus_field", chars: ["caesar", "antony"]), (scene: "pharsalus_line", chars: ["caesar", "antony"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-caesar.antony__pharsalus_line-caesar.pompey", panels: [(scene: "pharsalus_field", chars: ["caesar", "antony"]), (scene: "pharsalus_line", chars: ["caesar", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-caesar.pompey__pharsalus_line-antony.pompey", panels: [(scene: "pharsalus_field", chars: ["caesar", "pompey"]), (scene: "pharsalus_line", chars: ["antony", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-caesar.pompey__pharsalus_line-caesar.antony", panels: [(scene: "pharsalus_field", chars: ["caesar", "pompey"]), (scene: "pharsalus_line", chars: ["caesar", "antony"])]),
    (level: "pharsalus", name: "wrong__pharsalus_field-caesar.pompey__pharsalus_line-caesar.pompey", panels: [(scene: "pharsalus_field", chars: ["caesar", "pompey"]), (scene: "pharsalus_line", chars: ["caesar", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-antony.pompey__pharsalus_field-antony.pompey", panels: [(scene: "pharsalus_line", chars: ["antony", "pompey"]), (scene: "pharsalus_field", chars: ["antony", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-antony.pompey__pharsalus_field-caesar.antony", panels: [(scene: "pharsalus_line", chars: ["antony", "pompey"]), (scene: "pharsalus_field", chars: ["caesar", "antony"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-antony.pompey__pharsalus_field-caesar.pompey", panels: [(scene: "pharsalus_line", chars: ["antony", "pompey"]), (scene: "pharsalus_field", chars: ["caesar", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-caesar.antony__pharsalus_field-antony.pompey", panels: [(scene: "pharsalus_line", chars: ["caesar", "antony"]), (scene: "pharsalus_field", chars: ["antony", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-caesar.antony__pharsalus_field-caesar.antony", panels: [(scene: "pharsalus_line", chars: ["caesar", "antony"]), (scene: "pharsalus_field", chars: ["caesar", "antony"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-caesar.pompey__pharsalus_field-antony.pompey", panels: [(scene: "pharsalus_line", chars: ["caesar", "pompey"]), (scene: "pharsalus_field", chars: ["antony", "pompey"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-caesar.pompey__pharsalus_field-caesar.antony", panels: [(scene: "pharsalus_line", chars: ["caesar", "pompey"]), (scene: "pharsalus_field", chars: ["caesar", "antony"])]),
    (level: "pharsalus", name: "wrong__pharsalus_line-caesar.pompey__pharsalus_field-caesar.pompey", panels: [(scene: "pharsalus_line", chars: ["caesar", "pompey"]), (scene: "pharsalus_field", chars: ["caesar", "pompey"])]),
    ]
}
