#!/usr/bin/env python3
"""
Генерит ВСЕ полностью-заполненные расстановки уровня (все сцены по панелям × все размещения
героев, каждый слот занят) и пишет Swift-фикстуру для снапшот-тестов. Движок считает solved
и зашивает статус + «кто где» в имя.

Usage:  python3 tools/gen_arrangements.py [level_id ...]   (default: rubicon)
"""
import sys, json, itertools, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import simulate as S

char_defs, scenes, rules = S.load_content(ROOT / "Content" / "rome")
levels = {json.load(open(f))["id"]: json.load(open(f))
          for f in (ROOT / "Content").glob("*/levels/*.json")}

def scene_assignments(level):
    scn, n = level["scenes"], level["panels"]
    if len(scn) >= n:
        return list(itertools.permutations(scn, n))       # каждая сцена не более 1 раза
    return list(itertools.product(scn, repeat=n))          # сцен меньше панелей — с повтором

def hero_fills(assign, roster):
    per_panel = [list(itertools.combinations(roster, scenes[sid].get("slots", 2))) for sid in assign]
    return itertools.product(*per_panel)

def arrangements(level):
    roster = level["characters"]
    out = []
    for assign in scene_assignments(level):
        for fill in hero_fills(assign, roster):
            panels = [(sid, list(chars)) for sid, chars in zip(assign, fill)]
            w = S.initial_world(level)
            S.simulate([(s, list(c)) for s, c in panels], w, scenes, rules, char_defs)
            solved = S.goal_met(level["goal"], w)
            name = ("SOLVED" if solved else "wrong") + "__" + "__".join(
                f"{sid}-{'.'.join(chars) if chars else 'empty'}" for sid, chars in panels)
            out.append((solved, name, panels))
    # SOLVED сверху, затем стабильный порядок
    out.sort(key=lambda x: (not x[0], x[1]))
    return out

def swift_lit(panels):
    parts = ", ".join(
        '(scene: "%s", chars: [%s])' % (sid, ", ".join('"%s"' % c for c in chars))
        for sid, chars in panels)
    return "[%s]" % parts

def main():
    ids = sys.argv[1:] or ["rubicon"]
    rows = []
    for lid in ids:
        for solved, name, panels in arrangements(levels[lid]):
            rows.append('    (level: "%s", name: "%s", panels: %s),' % (lid, name, swift_lit(panels)))
    swift = ("// GENERATED by tools/gen_arrangements.py — do not edit by hand.\n"
             "enum GeneratedArrangements {\n"
             "    typealias Case = (level: String, name: String, panels: [(scene: String?, chars: [String])])\n"
             "    static let all: [Case] = [\n" + "\n".join(rows) + "\n    ]\n}\n")
    out = ROOT / "ios" / "Tests" / "Snapshot" / "GeneratedArrangements.swift"
    out.write_text(swift)
    print(f"wrote {out}  ({len(rows)} arrangements for {ids})")
    for lid in ids:
        a = arrangements(levels[lid]); ns = sum(1 for x in a if x[0])
        print(f"  {lid}: {len(a)} досок, из них SOLVED: {ns}")

if __name__ == "__main__":
    main()
